;; emma-theme.el --- Emma's official theme. Based on gruvbox and nord.

;;; Code:

(unless (>= emacs-major-version 24)
  (error "Emma theme requires Emacs 24 or later!"))

(deftheme emma "Official theme for Emma. Based on gruvbox")

;; 0 = 
;;
;;

;;; Color Constants
(let ((class '((class color) (min-colors 89)))
      (emma0 (if (display-graphic-p) "#282828" "#282828"))
      (emma1 (if (display-graphic-p) "#3C3836" "#3C3836"))
      (emma2 (if (display-graphic-p) "#504945" "#504945"))
      (emma3 (if (display-graphic-p) "#665C54" "#665C54"))
      (emma4 (if (display-graphic-p) "#D5C4A1" "#D5C4A1"))
      (emma5 (if (display-graphic-p) "#EBDBB2" "#EBDBB2"))
      (emma6 (if (display-graphic-p) "#FBF1F7" "#FBF1F7"))
      (emma7 (if (display-graphic-p) "#8EC07C" "#8EC07C"))
      (emma8 (if (display-graphic-p) "#83A598" "#83A598"))
      (emma9 (if (display-graphic-p) "#458588" "#458588"))
      (emma10 (if (display-graphic-p) "#689D6A" "#689D6A"))
      (emma11 (if (display-graphic-p) "#CC241D" "#CC241D"))
      (emma12 (if (display-graphic-p) "#FABD2F" "#FABD2F"))
      (emma13 (if (display-graphic-p) "#D79921" "#D79921"))
      (emma14(if (display-graphic-p) "#B8BB26" "#B8BB26"))
      (emma15 (if (display-graphic-p) "#B16286" "#B16286"))
      (emma-annotation (if (display-graphic-p) "#D65D0E" "#D65D0E"))
      (emma-attribute (if (display-graphic-p) "#8EC07C" "#8EC07C"))
      (emma-class (if (display-graphic-p) "#8EC07C" "#8EC07C"))
      (emma-comment (if (display-graphic-p) "#665C54" "#665C54"))
      (emma-escape (if (display-graphic-p) "#FABD2F" "#FABD2F"))
      (emma-method (if (display-graphic-p) "#83A598" "#83A598"))
      (emma-keyword (if (display-graphic-p) "#458588" "#458588"))
      (emma-numeric (if (display-graphic-p) "#B16286" "#B16286"))
      (emma-operator (if (display-graphic-p) "#458588" "#458588"))
      (emma-preprocessor (if (display-graphic-p) "#689D6A" "#689D6A"))
      (emma-punctuation (if (display-graphic-p) "#D5C4A1" "#D5C4A1"))
      (emma-regexp (if (display-graphic-p) "#D79921" "#D79921"))
      (emma-string (if (display-graphic-p) "#B8BB26" "#B8BB26"))
      (emma-tag (if (display-graphic-p) "#458588" "#458588"))
      (emma-variable (if (display-graphic-p) "#D5C4A1" "#D5C4A1")))
;;;; +------------+
;;;; + Core Faces +
;;;; +------------+
  (custom-theme-set-faces
    'emma
    ;; +--- Base ---+
    `(bold ((,class (:weight bold))))
    `(bold-italic ((,class (:weight bold :slant italic))))
    `(default ((,class (:foreground ,emma4 :background ,emma0))))
    `(error ((,class (:foreground ,emma11 :weight bold))))
    `(escape-glyph ((,class (:foreground ,emma12))))
    `(font-lock-builtin-face ((,class (:foreground ,emma9))))
    `(font-lock-comment-face ((,class (:foreground ,emma3))))
    `(font-lock-comment-delimiter-face ((,class (:foreground ,emma3))))
    `(font-lock-constant-face ((,class (:foreground ,emma9))))
    `(font-lock-doc-face ((,class (:foreground ,emma3))))
    `(font-lock-function-name-face ((,class (:foreground ,emma8))))
    `(font-lock-keyword-face ((,class (:foreground ,emma9))))
    `(font-lock-negation-char-face ((,class (:foreground ,emma9))))
    `(font-lock-preprocessor-face ((,class (:foreground ,emma10 :weight bold))))
    `(font-lock-reference-face ((,class (:foreground ,emma9))))
    `(font-lock-regexp-grouping-backslash ((,class (:foreground ,emma13))))
    `(font-lock-regexp-grouping-construct ((,class (:foreground ,emma13))))
    `(font-lock-string-face ((,class (:foreground ,emma14))))
    `(font-lock-type-face ((,class (:foreground ,emma7))))
    `(font-lock-variable-name-face ((,class (:foreground ,emma4))))
    `(font-lock-warning-face ((,class (:foreground ,emma13))))
    `(italic ((,class (:slant italic))))
    `(shadow ((,class (:foreground ,emma3))))
    `(underline ((,class (:underline t))))
    `(warning ((,class (:foreground ,emma13 :weight bold))))

    ;; +--- Syntax ---+
    ;; > C
    `(c-annotation-face ((,class (:foreground ,emma-annotation))))

    ;; > diff
    `(diff-added ((,class (:foreground ,emma14))))
    `(diff-changed ((,class (:foreground ,emma13))))
    `(diff-context ((,class (:inherit default))))
    `(diff-file-header ((,class (:foreground ,emma8))))
    `(diff-function ((,class (:foreground ,emma7))))
    `(diff-header ((,class (:foreground ,emma9 :weight bold))))
    `(diff-hunk-header ((,class (:foreground ,emma9 :background ,emma0))))
    `(diff-indicator-added ((,class (:foreground ,emma14))))
    `(diff-indicator-changed ((,class (:foreground ,emma13))))
    `(diff-indicator-removed ((,class (:foreground ,emma11))))
    `(diff-nonexistent ((,class (:foreground ,emma11))))
    `(diff-refine-added ((,class (:foreground ,emma14))))
    `(diff-refine-changed ((,class (:foreground ,emma13))))
    `(diff-refine-removed ((,class (:foreground ,emma11))))
    `(diff-removed ((,class (:foreground ,emma11))))

    ;; +--- UI ---+
    `(border ((,class (:foreground ,emma4))))
    `(buffer-menu-buffer ((,class (:foreground ,emma4 :weight bold))))
    `(button ((,class (:background ,emma0 :foreground ,emma8 :box (:line-width 2 :color ,emma4 :style sunken-button)))))
    `(completions-annotations ((,class (:foreground ,emma9))))
    `(completions-common-part ((,class (:foreground ,emma8 :weight bold))))
    `(completions-first-difference ((,class (:foreground ,emma11))))
    `(custom-button ((,class (:background ,emma0 :foreground ,emma8 :box (:line-width 2 :color ,emma4 :style sunken-button)))))
    `(custom-button-mouse ((,class (:background ,emma4 :foreground ,emma0 :box (:line-width 2 :color ,emma4 :style sunken-button)))))
    `(custom-button-pressed ((,class (:background ,emma6 :foreground ,emma0 :box (:line-width 2 :color ,emma4 :style sunken-button)))))
    `(custom-button-pressed-unraised ((,class (:background ,emma4 :foreground ,emma0 :box (:line-width 2 :color ,emma4 :style sunken-button)))))
    `(custom-button-unraised ((,class (:background ,emma0 :foreground ,emma8 :box (:line-width 2 :color ,emma4 :style sunken-button)))))
    `(custom-changed ((,class (:foreground ,emma13))))
    `(custom-comment ((,class (:foreground ,emma3))))
    `(custom-comment-tag ((,class (:foreground ,emma7))))
    `(custom-documentation ((,class (:foreground ,emma4))))
    `(custom-group-tag ((,class (:foreground ,emma8 :weight bold))))
    `(custom-group-tag-1 ((,class (:foreground ,emma8 :weight bold))))
    `(custom-invalid ((,class (:foreground ,emma11))))
    `(custom-modified ((,class (:foreground ,emma13))))
    `(custom-rogue ((,class (:foreground ,emma12 :background ,emma2))))
    `(custom-saved ((,class (:foreground ,emma14))))
    `(custom-set ((,class (:foreground ,emma8))))
    `(custom-state ((,class (:foreground ,emma14))))
    `(custom-themed ((,class (:foreground ,emma8 :background ,emma2))))
    `(cursor ((,class (:background ,emma4))))
    `(fringe ((,class (:foreground ,emma4 :background ,emma0))))
    `(file-name-shadow ((,class (:inherit shadow))))
    `(header-line ((,class (:foreground ,emma4 :background ,emma2))))
    `(help-argument-name ((,class (:foreground ,emma8))))
    `(highlight ((,class (:foreground ,emma8 :background ,emma2))))
    `(hl-line ((,class (:background ,emma1))))
    `(info-menu-star ((,class (:foreground ,emma9))))
    `(isearch ((,class (:foreground ,emma0 :background ,emma8))))
    `(isearch-fail ((,class (:foreground ,emma11))))
    `(link ((,class (:underline t))))
    `(link-visited ((,class (:underline t))))
    `(linum ((,class (:foreground ,emma3 :background ,emma0))))
    `(linum-relative-current-face ((,class (:foreground ,emma3 :background ,emma0))))
    `(match ((,class (:inherit isearch))))
    `(message-cited-text ((,class (:foreground ,emma4))))
    `(message-header-cc ((,class (:foreground ,emma9))))
    `(message-header-name ((,class (:foreground ,emma7))))
    `(message-header-newsgroup ((,class (:foreground ,emma14))))
    `(message-header-other ((,class (:foreground ,emma4))))
    `(message-header-subject ((,class (:foreground ,emma8))))
    `(message-header-to ((,class (:foreground ,emma9))))
    `(message-header-xheader ((,class (:foreground ,emma13))))
    `(message-mml ((,class (:foreground ,emma10))))
    `(message-separator ((,class (:inherit shadow))))
    `(minibuffer-prompt ((,class (:foreground ,emma8 :weight bold))))
    `(mm-command-output ((,class (:foreground ,emma8))))
    `(mode-line ((,class (:foreground ,emma4 :background ,emma2))))
    `(mode-line-buffer-id ((,class (:weight bold))))
    `(mode-line-highlight ((,class (:inherit highlight))))
    `(mode-line-inactive ((,class (:foreground ,emma4 :background ,emma1))))
    `(next-error ((,class (:inherit error))))
    `(nobreak-space ((,class (:foreground ,emma3))))
    `(outline-1 ((,class (:foreground ,emma8 :weight bold))))
    `(outline-2 ((,class (:inherit outline-1))))
    `(outline-3 ((,class (:inherit outline-1))))
    `(outline-4 ((,class (:inherit outline-1))))
    `(outline-5 ((,class (:inherit outline-1))))
    `(outline-6 ((,class (:inherit outline-1))))
    `(outline-7 ((,class (:inherit outline-1))))
    `(outline-8 ((,class (:inherit outline-1))))
    `(package-description ((,class (:foreground ,emma4))))
    `(package-help-section-name ((,class (:foreground ,emma8 :weight bold))))
    `(package-name ((,class (:foreground ,emma8))))
    `(package-status-available ((,class (:foreground ,emma7))))
    `(package-status-avail-obso ((,class (:foreground ,emma7 :slant italic))))
    `(package-status-built-in ((,class (:foreground ,emma9))))
    `(package-status-dependency ((,class (:foreground ,emma8 :slant italic))))
    `(package-status-disabled ((,class (:foreground ,emma3))))
    `(package-status-external ((,class (:foreground ,emma12 :slant italic))))
    `(package-status-held ((,class (:foreground ,emma4 :weight bold))))
    `(package-status-new ((,class (:foreground ,emma14))))
    `(package-status-incompat ((,class (:foreground ,emma11))))
    `(package-status-installed ((,class (:foreground ,emma7 :weight bold))))
    `(package-status-unsigned ((,class (:underline ,emma13))))
    `(query-replace ((,class (:foreground ,emma8 :background ,emma2))))
    `(region ((,class (:background ,emma2))))
    `(scroll-bar ((,class (:background ,emma3))))
    `(secondary-selection ((,class (:background ,emma2))))
    `(show-paren-match-face ((,class (:foreground ,emma0 :background ,emma8))))
    `(show-paren-mismatch-face ((,class (:background ,emma11))))
    `(success ((,class (:foreground ,emma14))))
    `(term ((,class (:foreground ,emma4 :background ,emma0))))
    `(term-color-black ((,class (:foreground ,emma1 :background ,emma1))))
    `(term-color-white ((,class (:foreground ,emma5 :background ,emma5))))
    `(term-color-cyan ((,class (:foreground ,emma7 :background ,emma7))))
    `(term-color-blue ((,class (:foreground ,emma8 :background ,emma8))))
    `(term-color-red ((,class (:foreground ,emma11 :background ,emma11))))
    `(term-color-yellow ((,class (:foreground ,emma13 :background ,emma13))))
    `(term-color-green ((,class (:foreground ,emma14 :background ,emma14))))
    `(term-color-magenta ((,class (:foreground ,emma15 :background ,emma15))))
    `(tool-bar ((,class (:foreground ,emma4 :background ,emma3))))
    `(tooltip ((,class (:foreground ,emma0 :background ,emma4))))
    `(trailing-whitespace ((,class (:foreground ,emma3))))
    `(tty-menu-disabled-face ((,class (:foreground ,emma1))))
    `(tty-menu-enabled-face ((,class (:background ,emma2 foreground ,emma4))))
    `(tty-menu-selected-face ((,class (:foreground ,emma8 :underline t))))
    `(undo-tree-visualizer-current-face ((,class (:foreground ,emma8))))
    `(undo-tree-visualizer-default-face ((,class (:foreground ,emma4))))
    `(undo-tree-visualizer-unmodified-face ((,class (:foreground ,emma4))))
    `(undo-tree-visualizer-register-face ((,class (:foreground ,emma9))))
    `(vc-conflict-state ((,class (:foreground ,emma12))))
    `(vc-edited-state ((,class (:foreground ,emma13))))
    `(vc-locally-added-state ((,class (:underline ,emma14))))
    `(vc-locked-state ((,class (:foreground ,emma10))))
    `(vc-missing-state ((,class (:foreground ,emma11))))
    `(vc-needs-update-state ((,class (:foreground ,emma12))))
    `(vc-removed-state ((,class (:foreground ,emma11))))
    `(vc-state-base ((,class (:foreground ,emma4))))
    `(vc-up-to-date-state ((,class (:foreground ,emma8))))
    `(vertical-border ((,class (:foreground ,emma2))))
    `(which-func ((,class (:foreground ,emma8))))
    `(whitespace-big-indent ((,class (:foreground ,emma3 :background ,emma0))))
    `(whitespace-empty ((,class (:foreground ,emma3 :background ,emma0))))
    `(whitespace-hspace ((,class (:foreground ,emma3 :background ,emma0))))
    `(whitespace-indentation ((,class (:foreground ,emma3 :background ,emma0))))
    `(whitespace-line ((,class (:background ,emma0))))
    `(whitespace-newline ((,class (:foreground ,emma3 :background ,emma0))))
    `(whitespace-space ((,class (:foreground ,emma3 :background ,emma0))))
    `(whitespace-space-after-tab ((,class (:foreground ,emma3 :background ,emma0))))
    `(whitespace-space-before-tab ((,class (:foreground ,emma3 :background ,emma0))))
    `(whitespace-tab ((,class (:foreground ,emma3 :background ,emma0))))
    `(whitespace-trailing ((,class (:inherit trailing-whitespace))))
    `(widget-button-pressed ((,class (:foreground ,emma9 :background ,emma1))))
    `(widget-documentation ((,class (:foreground ,emma4))))
    `(widget-field ((,class (:background ,emma2 :foreground ,emma4))))
    `(widget-single-line-field ((,class (:background ,emma2 :foreground ,emma4))))
    `(window-divider ((,class (:background ,emma3))))
    `(window-divider-first-pixel ((,class (:background ,emma3))))
    `(window-divider-last-pixel ((,class (:background ,emma3))))

    ;;;; +-----------------+
    ;;;; + Package Support +
    ;;;; +-----------------+
    ;; +--- Syntax ---+
    ;; > Auctex
    `(font-latex-bold-face ((,class (:inherit bold))))
    `(font-latex-italic-face ((,class (:inherit italic))))
    `(font-latex-math-face ((,class (:foreground ,emma8))))
    `(font-latex-sectioning-0-face ((,class (:foreground ,emma8 :weight bold))))
    `(font-latex-sectioning-1-face ((,class (:inherit font-latex-sectioning-0-face))))
    `(font-latex-sectioning-2-face ((,class (:inherit font-latex-sectioning-0-face))))
    `(font-latex-sectioning-3-face ((,class (:inherit font-latex-sectioning-0-face))))
    `(font-latex-sectioning-4-face ((,class (:inherit font-latex-sectioning-0-face))))
    `(font-latex-sectioning-5-face ((,class (:inherit font-latex-sectioning-0-face))))
    `(font-latex-script-char-face ((,class (:inherit font-lock-warning-face))))
    `(font-latex-string-face ((,class (:inherit font-lock-string-face))))
    `(font-latex-warning-face ((,class (:inherit font-lock-warning-face))))

    ;; > Elixir
    `(elixir-attribute-face ((,class (:foreground ,emma-annotation))))
    `(elixir-atom-face ((,class (:foreground ,emma4 :weight bold))))

    ;; > Enhanced Ruby
    `(enh-ruby-heredoc-delimiter-face ((,class (:foreground ,emma14))))
    `(enh-ruby-op-face ((,class (:foreground ,emma9))))
    `(enh-ruby-regexp-delimiter-face ((,class (:foreground ,emma13))))
    `(enh-ruby-regexp-face ((,class (:foreground ,emma13))))
    `(enh-ruby-string-delimiter-face ((,class (:foreground ,emma14))))
    `(erm-syn-errline ((,class (:foreground ,emma11 :underline t))))
    `(erm-syn-warnline ((,class (:foreground ,emma13 :underline t))))

    ;; > Java Development Environment for Emacs
    `(jdee-db-active-breakpoint-face ((,class (:background ,emma2 :weight bold))))
    `(jdee-bug-breakpoint-cursor ((,class (:background ,emma2))))
    `(jdee-db-requested-breakpoint-face ((,class (:foreground ,emma13 :background ,emma2 :weight bold))))
    `(jdee-db-spec-breakpoint-face ((,class (:foreground ,emma14 :background ,emma2 :weight bold))))
    `(jdee-font-lock-api-face ((,class (:foreground ,emma4))))
    `(jdee-font-lock-code-face ((,class (:slant italic))))
    `(jdee-font-lock-constant-face ((,class (:foreground ,emma-keyword))))
    `(jdee-font-lock-constructor-face ((,class (:foreground ,emma-method))))
    `(jdee-font-lock-doc-tag-face ((,class (:foreground ,emma7))))
    `(jdee-font-lock-link-face ((,class (:underline t))))
    `(jdee-font-lock-modifier-face ((,class (:foreground ,emma-keyword))))
    `(jdee-font-lock-number-face ((,class (:foreground ,emma-numeric))))
    `(jdee-font-lock-operator-fac ((,class (:foreground ,emma-operator))))
    `(jdee-font-lock-package-face ((,class (:foreground ,emma-class))))
    `(jdee-font-lock-pre-face ((,class (:foreground ,emma-comment :slant italic))))
    `(jdee-font-lock-private-face ((,class (:foreground ,emma-keyword))))
    `(jdee-font-lock-public-face ((,class (:foreground ,emma-keyword))))
    `(jdee-font-lock-variable-face ((,class (:foreground ,emma-variable))))

    ;; > JavaScript 2
    `(js2-function-call ((,class (:foreground ,emma8))))
    `(js2-private-function-call ((,class (:foreground ,emma8))))
    `(js2-jsdoc-html-tag-delimiter ((,class (:foreground ,emma6))))
    `(js2-jsdoc-html-tag-name ((,class (:foreground ,emma9))))
    `(js2-external-variable ((,class (:foreground ,emma4))))
    `(js2-function-param ((,class (:foreground ,emma4))))
    `(js2-jsdoc-value ((,class (:foreground ,emma3))))
    `(js2-jsdoc-tag ((,class (:foreground ,emma7))))
    `(js2-jsdoc-type ((,class (:foreground ,emma7))))
    `(js2-private-member ((,class (:foreground ,emma4))))
    `(js2-object-property ((,class (:foreground ,emma4))))
    `(js2-error ((,class (:foreground ,emma11))))
    `(js2-warning ((,class (:foreground ,emma13))))
    `(js2-instance-member ((,class (:foreground ,emma4))))

    ;; > JavaScript 3
    `(js3-error-face ((,class (:foreground ,emma11))))
    `(js3-external-variable-face ((,class (:foreground ,emma4))))
    `(js3-function-param-face ((,class (:foreground ,emma4))))
    `(js3-instance-member-face ((,class (:foreground ,emma4))))
    `(js3-jsdoc-html-tag-delimiter-face ((,class (:foreground ,emma6))))
    `(js3-jsdoc-html-tag-name-face ((,class (:foreground ,emma9))))
    `(js3-jsdoc-tag-face ((,class (:foreground ,emma9))))
    `(js3-jsdoc-type-face ((,class (:foreground ,emma7))))
    `(js3-jsdoc-value-face ((,class (:foreground ,emma4))))
    `(js3-magic-paren-face ((,class (:inherit show-paren-match-face))))
    `(js3-private-function-call-face ((,class (:foreground ,emma8))))
    `(js3-private-member-face ((,class (:foreground ,emma4))))
    `(js3-warning-face ((,class (:foreground ,emma13))))

    ;; > Markdown
    `(markdown-blockquote-face ((,class (:foreground ,emma3))))
    `(markdown-bold-face ((,class (:inherit bold))))
    `(markdown-header-face-1 ((,class (:foreground ,emma8))))
    `(markdown-header-face-2 ((,class (:foreground ,emma8))))
    `(markdown-header-face-3 ((,class (:foreground ,emma8))))
    `(markdown-header-face-4 ((,class (:foreground ,emma8))))
    `(markdown-header-face-5 ((,class (:foreground ,emma8))))
    `(markdown-header-face-6 ((,class (:foreground ,emma8))))
    `(markdown-inline-code-face ((,class (:foreground ,emma7))))
    `(markdown-italic-face ((,class (:inherit italic))))
    `(markdown-link-face ((,class (:foreground ,emma8))))
    `(markdown-markup-face ((,class (:foreground ,emma9))))
    `(markdown-reference-face ((,class (:inherit markdown-link-face))))
    `(markdown-url-face ((,class (:foreground ,emma4 :underline t))))

    ;; > Rainbow Delimeters
    `(rainbow-delimiters-depth-1-face ((,class :foreground ,emma7)))
    `(rainbow-delimiters-depth-2-face ((,class :foreground ,emma8)))
    `(rainbow-delimiters-depth-3-face ((,class :foreground ,emma9)))
    `(rainbow-delimiters-depth-4-face ((,class :foreground ,emma10)))
    `(rainbow-delimiters-depth-5-face ((,class :foreground ,emma12)))
    `(rainbow-delimiters-depth-6-face ((,class :foreground ,emma13)))
    `(rainbow-delimiters-depth-7-face ((,class :foreground ,emma14)))
    `(rainbow-delimiters-depth-8-face ((,class :foreground ,emma15)))
    `(rainbow-delimiters-unmatched-face ((,class :foreground ,emma11)))

    ;; > Web Mode
    `(web-mode-attr-tag-custom-face ((,class (:foreground ,emma-attribute))))
    `(web-mode-builtin-face ((,class (:foreground ,emma-keyword))))
    `(web-mode-comment-face ((,class (:foreground ,emma-comment))))
    `(web-mode-comment-keyword-face ((,class (:foreground ,emma-comment))))
    `(web-mode-constant-face ((,class (:foreground ,emma-variable))))
    `(web-mode-css-at-rule-face ((,class (:foreground ,emma-annotation))))
    `(web-mode-css-function-face ((,class (:foreground ,emma-method))))
    `(web-mode-css-property-name-face ((,class (:foreground ,emma-keyword))))
    `(web-mode-css-pseudo-class-face ((,class (:foreground ,emma-class))))
    `(web-mode-css-selector-face ((,class (:foreground ,emma-keyword))))
    `(web-mode-css-string-face ((,class (:foreground ,emma-string))))
    `(web-mode-doctype-face ((,class (:foreground ,emma-preprocessor))))
    `(web-mode-function-call-face ((,class (:foreground ,emma-method))))
    `(web-mode-function-name-face ((,class (:foreground ,emma-method))))
    `(web-mode-html-attr-name-face ((,class (:foreground ,emma-attribute))))
    `(web-mode-html-attr-equal-face ((,class (:foreground ,emma-punctuation))))
    `(web-mode-html-attr-value-face ((,class (:foreground ,emma-string))))
    `(web-mode-html-entity-face ((,class (:foreground ,emma-keyword))))
    `(web-mode-html-tag-bracket-face ((,class (:foreground ,emma-punctuation))))
    `(web-mode-html-tag-custom-face ((,class (:foreground ,emma-tag))))
    `(web-mode-html-tag-face ((,class (:foreground ,emma-tag))))
    `(web-mode-html-tag-namespaced-face ((,class (:foreground ,emma-keyword))))
    `(web-mode-json-key-face ((,class (:foreground ,emma-class))))
    `(web-mode-json-string-face ((,class (:foreground ,emma-string))))
    `(web-mode-keyword-face ((,class (:foreground ,emma-keyword))))
    `(web-mode-preprocessor-face ((,class (:foreground ,emma-preprocessor))))
    `(web-mode-string-face ((,class (:foreground ,emma-string))))
    `(web-mode-symbol-face ((,class (:foreground ,emma-variable))))
    `(web-mode-type-face ((,class (:foreground ,emma-class))))
    `(web-mode-warning-face ((,class (:inherit ,font-lock-warning-face))))
    `(web-mode-variable-name-face ((,class (:foreground ,emma-variable))))

    ;; +--- UI ---+
    ;; > Anzu
    `(anzu-mode-line ((,class (:foreground, emma8))))
    `(anzu-mode-line-no-match ((,class (:foreground, emma11))))

    ;; > Avy
    `(avy-lead-face ((,class (:background ,emma11 :foreground ,emma5))))
    `(avy-lead-face-0 ((,class (:background ,emma10 :foreground ,emma5))))
    `(avy-lead-face-1 ((,class (:background ,emma3 :foreground ,emma5))))
    `(avy-lead-face-2 ((,class (:background ,emma15 :foreground ,emma5))))

    ;; > Company
    `(company-echo-common ((,class (:foreground ,emma0 :background ,emma4))))
    `(company-preview ((,class (:foreground ,emma4 :background ,emma10))))
    `(company-preview-common ((,class (:foreground ,emma0 :background ,emma8))))
    `(company-preview-search ((,class (:foreground ,emma0 :background ,emma8))))
    `(company-scrollbar-bg ((,class (:foreground ,emma1 :background ,emma1))))
    `(company-scrollbar-fg ((,class (:foreground ,emma2 :background ,emma2))))
    `(company-template-field ((,class (:foreground ,emma0 :background ,emma7))))
    `(company-tooltip ((,class (:foreground ,emma4 :background ,emma2))))
    `(company-tooltip-annotation ((,class (:foreground ,emma12))))
    `(company-tooltip-annotation-selection ((,class (:foreground ,emma12 :weight bold))))
    `(company-tooltip-common ((,class (:foreground ,emma8))))
    `(company-tooltip-common-selection ((,class (:foreground ,emma8 :background ,emma3))))
    `(company-tooltip-mouse ((,class (:inherit highlight))))
    `(company-tooltip-selection ((,class (:background ,emma3 :weight bold))))

    ;; > diff-hl
   `(diff-hl-change ((,class (:background ,emma13))))
   `(diff-hl-insert ((,class (:background ,emma14))))
   `(diff-hl-delete ((,class (:background ,emma11))))
   
    ;; > Evil
    `(evil-ex-info ((,class (:foreground ,emma8))))
    `(evil-ex-substitute-replacement ((,class (:foreground ,emma9))))
    `(evil-ex-substitute-matches ((,class (:inherit isearch))))

    ;; > Flycheck
    `(flycheck-error ((,class (:underline (:style wave :color ,emma11)))))
    `(flycheck-fringe-error ((,class (:foreground ,emma11 :weight bold))))
    `(flycheck-fringe-info ((,class (:foreground ,emma8 :weight bold))))
    `(flycheck-fringe-warning ((,class (:foreground ,emma13 :weight bold))))
    `(flycheck-info ((,class (:underline (:style wave :color ,emma8)))))
    `(flycheck-warning ((,class (:underline (:style wave :color ,emma13)))))

    ;; > Git Gutter
    `(git-gutter:modified ((,class (:foreground ,emma13))))
    `(git-gutter:added ((,class (:foreground ,emma14))))
    `(git-gutter:deleted ((,class (:foreground ,emma11))))

    ;; > Git Gutter Plus
    `(git-gutter+-modified ((,class (:foreground ,emma13))))
    `(git-gutter+-added ((,class (:foreground ,emma14))))
    `(git-gutter+-deleted ((,class (:foreground ,emma11))))

    ;; > Helm
    `(helm-bookmark-addressbook ((,class (:foreground ,emma7))))
    `(helm-bookmark-directory ((,class (:foreground ,emma9))))
    `(helm-bookmark-file ((,class (:foreground ,emma8))))
    `(helm-bookmark-gnus ((,class (:foreground ,emma10))))
    `(helm-bookmark-info ((,class (:foreground ,emma14))))
    `(helm-bookmark-man ((,class (:foreground ,emma4))))
    `(helm-bookmark-w3m ((,class (:foreground ,emma9))))
    `(helm-buffer-directory ((,class (:foreground ,emma9))))
    `(helm-buffer-file ((,class (:foreground ,emma8))))
    `(helm-buffer-not-saved ((,class (:foreground ,emma13))))
    `(helm-buffer-process ((,class (:foreground ,emma10))))
    `(helm-candidate-number ((,class (:foreground ,emma4 :weight bold))))
    `(helm-candidate-number-suspended ((,class (:foreground ,emma4))))
    `(helm-ff-directory ((,class (:foreground ,emma9 :weight bold))))
    `(helm-ff-dirs ((,class (:foreground ,emma9))))
    `(helm-ff-dotted-director ((,class (:foreground ,emma9 :underline t))))
    `(helm-ff-dotted-symlink-director ((,class (:foreground ,emma7 :weight bold))))
    `(helm-ff-executable ((,class (:foreground ,emma8))))
    `(helm-ff-file ((,class (:foreground ,emma4))))
    `(helm-ff-invalid-symlink ((,class (:foreground ,emma11 :weight bold))))
    `(helm-ff-prefix ((,class (:foreground ,emma0 :background ,emma9))))
    `(helm-ff-symlink ((,class (:foreground ,emma7))))
    `(helm-grep-cmd-line ((,class (:foreground ,emma4 :background ,emma0))))
    `(helm-grep-file ((,class (:foreground ,emma8))))
    `(helm-grep-finish ((,class (:foreground ,emma5))))
    `(helm-grep-lineno ((,class (:foreground ,emma4))))
    `(helm-grep-match ((,class (:inherit isearch))))
    `(helm-grep-running ((,class (:foreground ,emma8))))
    `(helm-header ((,class (:foreground ,emma9 :background ,emma2))))
    `(helm-header-line-left-margin ((,class (:foreground ,emma9 :background ,emma2))))
    `(helm-history-deleted ((,class (:foreground ,emma11))))
    `(helm-history-remote ((,class (:foreground ,emma4))))
    `(helm-lisp-completion-info ((,class (:foreground ,emma4 :weight bold))))
    `(helm-lisp-show-completion ((,class (:inherit isearch))))
    `(helm-locate-finish ((,class (:foreground ,emma14))))
    `(helm-match ((,class (:foreground ,emma8))))
    `(helm-match-item ((,class (:inherit isearch))))
    `(helm-moccur-buffer ((,class (:foreground ,emma8))))
    `(helm-resume-need-update ((,class (:foreground ,emma0 :background ,emma13))))
    `(helm-selection ((,class (:inherit highlight))))
    `(helm-selection-line ((,class (:background ,emma2))))
    `(helm-source-header ((,class (:height 1.44 :foreground ,emma8 :background ,emma2))))
    `(helm-swoop-line-number-face ((,class (:foreground ,emma4 :background ,emma0))))
    `(helm-swoop-target-word-face ((,class (:foreground ,emma0 :background ,emma7))))
    `(helm-swoop-target-line-face ((,class (:background ,emma13 :foreground ,emma3))))
    `(helm-swoop-target-line-block-face ((,class (:background ,emma13 :foreground ,emma3))))
    `(helm-separator ((,class (:background ,emma2))))
    `(helm-visible-mark ((,class (:background ,emma2))))

    ;; > Magit
    `(magit-branch ((,class (:foreground ,emma7 :weight bold))))
    `(magit-diff-context-highlight ((,class (:background ,emma2))))
    `(magit-diff-file-header ((,class (:foreground ,emma8 :box (:color ,emma8)))))
    `(magit-diffstat-added ((,class (:foreground ,emma14))))
    `(magit-diffstat-removed ((,class (:foreground ,emma11))))
    `(magit-hash ((,class (:foreground ,emma8))))
    `(magit-hunk-heading ((,class (:foreground ,emma9))))
    `(magit-hunk-heading-highlight ((,class (:foreground ,emma9 :background ,emma2))))
    `(magit-item-highlight ((,class (:foreground ,emma8 :background ,emma2))))
    `(magit-log-author ((,class (:foreground ,emma7))))
    `(magit-process-ng ((,class (:foreground ,emma13 :weight bold))))
    `(magit-process-ok ((,class (:foreground ,emma14 :weight bold))))
    `(magit-section-heading ((,class (:foreground ,emma7 :weight bold))))
    `(magit-section-highlight ((,class (:background ,emma2))))

    ;; > MU4E
    `(mu4e-header-marks-face ((,class (:foreground ,emma9))))
    `(mu4e-title-face ((,class (:foreground ,emma8))))
    `(mu4e-header-key-face ((,class (:foreground ,emma8))))
    `(mu4e-highlight-face ((,class (:highlight))))
    `(mu4e-flagged-face ((,class (:foreground ,emma13))))
    `(mu4e-unread-face ((,class (:foreground ,emma13 :weight bold))))
    `(mu4e-link-face ((,class (:underline t))))

    ;; > Powerline
    `(powerline-active1 ((,class (:foreground ,emma4 :background ,emma1))))
    `(powerline-active2 ((,class (:foreground ,emma4 :background ,emma3))))
    `(powerline-inactive1 ((,class (:background ,emma2))))
    `(powerline-inactive2 ((,class (:background ,emma2))))

    ;; > Powerline Evil
    `(powerline-evil-base-face ((,class (:foreground ,emma4))))
    `(powerline-evil-normal-face ((,class (:background ,emma8))))
    `(powerline-evil-insert-face ((,class (:foreground ,emma0 :background ,emma4))))
    `(powerline-evil-visual-face ((,class (:foreground ,emma0 :background ,emma7))))
    `(powerline-evil-replace-face ((,class (:foreground ,emma0 :background ,emma9))))

    ;; > NeoTree
    `(neo-banner-face ((,class (:foreground ,emma10))))
    `(neo-dir-link-face ((,class (:foreground ,emma9))))
    `(neo-expand-btn-face ((,class (:foreground ,emma6 :bold t))))
    `(neo-file-link-face ((,class (:foreground ,emma4))))
    `(neo-root-dir-face ((,class (:foreground ,emma7 :weight bold))))
    `(neo-vc-added-face ((,class (:foreground ,emma14))))
    `(neo-vc-conflict-face ((,class (:foreground ,emma11))))
    `(neo-vc-default-face ((,class (:foreground ,emma4))))
    `(neo-vc-edited-face ((,class (:foreground ,emma13))))
    `(neo-vc-ignored-face ((,class (:foreground ,emma3))))
    `(neo-vc-missing-face ((,class (:foreground ,emma12))))
    `(neo-vc-needs-merge-face ((,class (:background ,emma12 :foreground ,emma4))))
    `(neo-vc-needs-update-face ((,class (:background ,emma10 :foreground ,emma4))))
    `(neo-vc-removed-face ((,class (:foreground ,emma11 :strike-through nil))))
    `(neo-vc-up-to-date-face ((,class (:foreground ,emma4))))
    `(neo-vc-user-face ((,class (:foreground ,emma4))))

    ;; > Org
    `(org-level-1 ((,class (:foreground ,emma8 :weight bold))))
    `(org-level-2 ((,class (:inherit org-level-1))))
    `(org-level-3 ((,class (:inherit org-level-1))))
    `(org-level-4 ((,class (:inherit org-level-1))))
    `(org-level-5 ((,class (:inherit org-level-1))))
    `(org-level-6 ((,class (:inherit org-level-1))))
    `(org-level-7 ((,class (:inherit org-level-1))))
    `(org-level-8 ((,class (:inherit org-level-1))))
    `(org-agenda-structure ((,class (:foreground ,emma9))))
    `(org-agenda-date ((,class (:foreground ,emma8 :underline nil))))
    `(org-agenda-done ((,class (:foreground ,emma14))))
    `(org-agenda-dimmed-todo-face ((,class (:background ,emma13))))
    `(org-block ((,class (:foreground ,emma4))))
    `(org-block-background ((,class (:background ,emma0))))
    `(org-block-begin-line ((,class (:foreground ,emma7))))
    `(org-block-end-line ((,class (:foreground ,emma7))))
    `(org-checkbox ((,class (:foreground ,emma9))))
    `(org-checkbox-statistics-done ((,class (:foreground ,emma14))))
    `(org-checkbox-statistics-todo ((,class (:foreground ,emma13))))
    `(org-code ((,class (:foreground ,emma7))))
    `(org-column ((,class (:background ,emma2))))
    `(org-column-title ((,class (:inherit org-column :weight bold :underline t))))
    `(org-date ((,class (:foreground ,emma8))))
    `(org-document-info ((,class (:foreground ,emma4))))
    `(org-document-info-keyword ((,class (:foreground ,emma3 :weight bold))))
    `(org-document-title ((,class (:foreground ,emma8 :weight bold))))
    `(org-done ((,class (:foreground ,emma14 :weight bold))))
    `(org-ellipsis ((,class (:foreground ,emma3))))
    `(org-footnote ((,class (:foreground ,emma8))))
    `(org-formula ((,class (:foreground ,emma9))))
    `(org-hide ((,class (:foreground ,emma0 :background ,emma0))))
    `(org-link ((,class (:underline t))))
    `(org-scheduled ((,class (:foreground ,emma14))))
    `(org-scheduled-previously ((,class (:foreground ,emma13))))
    `(org-scheduled-today ((,class (:foreground ,emma8))))
    `(org-special-keyword ((,class (:foreground ,emma9))))
    `(org-table ((,class (:foreground ,emma9))))
    `(org-todo ((,class (:foreground ,emma13 :weight bold))))
    `(org-upcoming-deadline ((,class (:foreground ,emma12))))
    `(org-warning ((,class (:foreground ,emma13 :weight bold))))
    `(font-latex-bold-face ((,class (:inherit bold))))
    `(font-latex-italic-face ((,class (:slant italic))))
    `(font-latex-string-face ((,class (:foreground ,emma14))))
    `(font-latex-match-reference-keywords ((,class (:foreground ,emma9))))
    `(font-latex-match-variable-keywords ((,class (:foreground ,emma4))))
    `(ido-only-match ((,class (:foreground ,emma8))))
    `(org-sexp-date ((,class (:foreground ,emma7))))
    `(ido-first-match ((,class (:foreground ,emma8 :weight bold))))
    `(ido-subdir ((,class (:foreground ,emma9))))
    `(org-quote ((,class (:inherit org-block :slant italic))))
    `(org-verse ((,class (:inherit org-block :slant italic))))
    `(org-agenda-date-weekend ((,class (:foreground ,emma9))))
    `(org-agenda-date-today ((,class (:foreground ,emma8 :weight bold))))
    `(org-agenda-done ((,class (:foreground ,emma14))))
    `(org-verbatim ((,class (:foreground ,emma7))))))

;;;###autoload
(when (and (boundp 'custom-theme-load-path) load-file-name)
  (add-to-list 'custom-theme-load-path
    (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'emma)

;; Local Variables:
;; no-byte-compile: t
;; indent-tabs-mode: nil
;; End:

;;; emma-theme.el ends here
